(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
    ((DEFAULT-MODES (APPEND '(BLOCKER-MODE) %SLOT-DEFAULT))))

(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES (APPEND '(EMACS-MODE) %SLOT-DEFAULT))))
