#!/bin/sh

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# start gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components keyring,pkcs11,ssh)
export SSH_AUTH_SOCK

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
