#!/bin/bash

# move mail in INBOX folder with spam to Trash directory
# notmuch search --output=files utkarsh190601@gmail.com/[Gmail].INBOX and tag:spam | xargs mv -t ~/.local/share/mail/utkarsh190601@gmail.com/[Gmail].Trash/cur/

# receive mail
mbsync -a
